export default defineEventHandler((event) => {
  return [
    {
      level: 0,
      name: "À l'essai",
      content: ['Popularité: Peut voter', 'Fringue: Pack fringues de débutant'],
      number: 514,
    },
    {
      level: 1,
      name: 'Noob',
      content: ['Fringue: Sidaction, Recyclades'],
      number: 64,
    },
    {
      level: 2,
      name: 'Bizutable',
      content: ['Fringue: Kagoul'],
      number: 47,
    },
    {
      level: 3,
      name: 'Bleu',
      content: ['Fringue: Pâques'],
      number: 39,
    },
    {
      level: 4,
      name: 'Neophyte',
      content: ['Fringue: Maillots de bains, badges Pays'],
      number: 24,
    },
    {
      level: 5,
      name: 'Apprentice',
      content: ["Groupes: Peut s'inscrire à 1 groupe", 'Fringue: Pâques, Halloween'],
      number: 18,
    },
    {
      level: 6,
      name: 'Initié',
      content: ['Fringue: 2 coiffures supplémentaires'],
      number: 16,
    },
    {
      level: 7,
      name: 'Trainy',
      content: ['Fringue: fringues Redromic'],
      number: 5,
    },
    {
      level: 8,
      name: 'Panawak',
      content: ['Fringue: Babouches, lunettes de ski'],
      number: 9,
    },
    {
      level: 9,
      name: 'Trustable',
      content: ['Fringue: Pattes de lapin'],
      number: 15,
    },
    {
      level: 10,
      name: 'Classe B.',
      content: ['Fringue: 2 paires de chaussures, un sac à dos'],
      number: 6,
    },
    {
      level: 11,
      name: 'Nice',
      content: ['Fringue: 2 maillots de bain'],
      number: 4,
    },
    {
      level: 12,
      name: 'Used',
      content: ['Fringue: masque de dragon'],
      number: 8,
    },
    {
      level: 13,
      name: 'Confirmé',
      content: ['Popularité: Ton vote compte pour 2', 'Fringue: Bois de renne'],
      number: 4,
    },
    {
      level: 14,
      name: 'Kostoz',
      content: ['Fringue: Pâques'],
      number: 1,
    },
    {
      level: 15,
      name: 'Classe A.',
      content: ["Groupes: Peut s'inscrire à 2 groupes", 'Groupes: Peut ouvrir 1 groupe'],
      number: 3,
    },
    {
      level: 16,
      name: 'Experimenté',
      content: ['Fringue: Coiffure Ketou'],
      number: 2,
    },
    {
      level: 17,
      name: 'Acharné',
      content: ['Fringue: 2 coiffures supplémentaires'],
      number: 5,
    },
    {
      level: 18,
      name: 'Respekt',
      content: ['Popularité: Ton vote compte pour 3', 'Fringue: Pâques'],
      number: 1,
    },
    {
      level: 19,
      name: '2High',
      content: ['Fringue: 1 paire de chaussures'],
      number: 4,
    },
    {
      level: 20,
      name: 'Classe Z.',
      content: ["Groupes: Peut s'inscrire à 3 groupes", 'Popularité: Ton vote compte pour 4'],
      number: 5,
    },
    {
      level: 21,
      name: 'Modoizable',
      content: ['Fringue: 2 tenues complètes Ultimoz'],
      number: 6,
    },
    {
      level: 22,
      name: 'Ultimoz C.',
      content: ['Fringue: Barbe blanche'],
      number: 6,
    },
    {
      level: 23,
      name: 'Ultimoz B.',
      content: ['Fringue: Masque de Rozwell'],
      number: 3,
    },
    {
      level: 24,
      name: 'Ultimoz A.',
      content: ['Fringue: Coupe Spéciale'],
      number: 3,
    },
    {
      level: 25,
      name: 'Ultimoz',
      content: ['Groupe: Peut créer un deuxième groupe'],
      number: 33,
    },
  ];
});
