export default defineEventHandler((event) => {
  return [
    {
      user: {
        name: 'ChAtEuX',
        id: 9,
        color: '',
        look: {
          avatar: 0,
          emote: 'angry',
          hat: 287,
          body: 358,
          shoe: 1015,
          item0: 800,
          item1: 937,
          item2: 974,
        },
      },
      id: 5,
      msgid: 169,
      date: 1646386775000,
      content: 'Sowkenebe',
    },
    {
      user: {
        name: 'ChAtEuX',
        id: 9,
        color: '',
        look: {
          avatar: 0,
          emote: 'angry',
          hat: 287,
          body: 358,
          shoe: 1015,
          item0: 800,
          item1: 937,
          item2: 974,
        },
      },
      id: 34,
      msgid: 154,
      date: 1640360984000,
      content: 'bite bite bitten',
    },
    {
      user: {
        name: 'Chelha',
        id: 3,
        color: '',
        look: {
          avatar: 0,
          emote: 'neutral',
          hat: 62,
          body: 1022,
          shoe: 1010,
          item0: 808,
          item1: 868,
          item2: 938,
        },
      },
      id: 33,
      msgid: 148,
      date: 1639584520000,
      content: 'test',
    },
    {
      user: {
        name: 'Guruji',
        id: 67,
        color: '',
        look: {
          avatar: 0,
          emote: 'vv',
          hat: 93,
          body: 378,
          shoe: 639,
          item0: 794,
          item1: 909,
          item2: 938,
        },
      },
      id: 14,
      msgid: 125,
      date: 1638867988000,
      content: 'blabla 💬',
    },
    {
      user: {
        name: 'IceTeaZouneT',
        id: 49,
        color: '',
        look: {
          avatar: 0,
          emote: 'smirk',
          hat: 196,
          body: 323,
          shoe: 640,
          item0: 808,
          item1: 879,
          item2: 938,
        },
      },
      id: 27,
      msgid: 86,
      date: 1631972244000,
      content: 'Okay super ! \n\nSans soucis si je drop Ã§a je pense direct Ã  toi pour le trade ! \n\nEncore merci Ã  toi :)',
    },
    {
      user: {
        name: 'Froidasse',
        id: 20,
        color: '',
        look: {
          avatar: 0,
          emote: 'neutral',
          hat: 135,
          body: 318,
          shoe: 1016,
          item0: 808,
          item1: 868,
          item2: 938,
        },
      },
      id: 16,
      msgid: 54,
      date: 1622970493000,
      content: 'Merci heureusement que t la calinou\nJv vite la recadrer.\nBisous luv ',
    },
  ];
});
