type User = {
  id: number;
  pseudo: string;
  email: string;
  regdate: string;
  lastvisit: string;
  money: string;
  avatar_design: string;
  signature: string;
  website: string;
  interest1: string;
  interest2: string;
  interest3: string;
  interest4: string;
  posts: string;
  avatar_mood: string;
  gender: string;
  level_time: string;
  actif: string;
  banned: null;
  admin: string;
  user_level: string;
  level: string;
  currentPet: string;
  loginToHome: string;
  sign: string;
  online: string;
  room: string;
  sid: string;
  loterie: string;
  fermla: null;
  updated_at: string;
};

export default User;
