name: PR Tests
'on': pull_request
jobs:
  hook:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - name: Typecheck
    run: npm run typecheck
    - name: Tests
    run: npm run test
      