name: PR Tests
'on': pull_request
jobs:
  tests:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run typecheck
      name: Typecheck
    - run: npm run test
      name: Tests
      