name: PR Tests
'on': pull_request
jobs:
  prepare:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci 
  typecheck:
    needs: [prepare]
    steps:
      - run: npm run typecheck
  test:
    needs: [prepare]
    steps:
      - run: npm run test

      name: PR Hooks
